site_name: Notebook
repo_url: https://github.com/haoda-li/notebook
edit_uri: blob/master/notebook/
site_author: Haoda Li
use_directory_urls: false
docs_dir: "notebook"

nav:
  - Courses: index.md
  - Notes:
    - Research Notes:
      - notes/research/llama.md
      - notes/research/trainium.md
    - Common Tool Cheatsheets:
      - notes/tools/proto.md
      - notes/tools/git.md
  - CS - VCCG:
    - CS294-173 Learning for 3D Seminar:
      - vccg/cs294173/intro.md
      - vccg/cs294173/optical_flow.md
      - vccg/cs294173/supervised3d.md
      - vccg/cs294173/pointcloud.md
      - vccg/cs294173/nerf.md
      - vccg/cs294173/shl.md
      - vccg/cs294173/sdf_nerf.md
      - vccg/cs294173/3dgaussian.md
      - vccg/cs294173/3dgsmath.md
      - vccg/cs294173/rotations.md
    - CS284A Computer Graphics and Imaging:
      - vccg/cs284/sampling.md
      - vccg/cs284/transforms.md
      - vccg/cs284/texture.md
      - vccg/cs284/splines.md
      - vccg/cs284/mesh.md
      - vccg/cs284/raytracing.md
      - vccg/cs284/mcintegral.md
      - vccg/cs284/pathtracing.md
      - vccg/cs284/camera.md
      - vccg/cs284/kinematics.md
      - vccg/cs284/simulation.md
      - vccg/cs284/fluids.md
      - vccg/cs284/color.md
    - CSC418 Computer Graphics:
      - vccg/csc418/raster_image.md
      - vccg/csc418/meshes.md
      - vccg/csc418/bvh.md
      - vccg/csc418/shader_pipeline.md
      - vccg/csc418/kinematics.md
      - vccg/csc418/mass_spring_system.md
    - CSC417/2549 Physics-based Animation:
      - vccg/csc417/introduction.md
      - vccg/csc417/1d_mass_spring.md
      - vccg/csc417/3d_mass_spring_system.md
      - vccg/csc417/fem.md
      - vccg/csc417/cloth.md
      - vccg/csc417/rigid_bodies.md
      - vccg/csc417/rotations.md
      - vccg/csc417/collision.md
      - vccg/csc417/fluids.md
    - CSC419/2520 Geometry Processing:
      - vccg/csc419/introduction.md
      - vccg/csc419/surface_reconstruction.md
      - vccg/csc419/registration.md
      - vccg/csc419/sparse_icp.md
      - vccg/csc419/smoothing.md
      - vccg/csc419/deformation.md
      - vccg/csc419/parameterization.md
      - vccg/csc419/curvature.md
    - CSC320 Intro. Visual Computing:
      - vccg/csc320/camera.md
      - vccg/csc320/matting.md
      - vccg/csc320/hdr.md
      - vccg/csc320/blending.md
      - vccg/csc320/poly_fitting.md
      - vccg/csc320/wavelet.md
    - CSC420 Intro. Image Understanding:
      - vccg/csc420/linear_filters.md
      - vccg/csc420/edge_detection.md
      - vccg/csc420/image_pyramids.md
      - vccg/csc420/harris_corner_detector.md
      - vccg/csc420/blob_detection.md
      - vccg/csc420/sift.md
      - vccg/csc420/camera_model.md
      - vccg/csc420/stereo.md
      - vccg/csc420/indexing.md

  - CS - AIML:
    - CSC412/2506 Probabilistic Learning and Reasoning:
      - aiml/csc412/models.md
      - aiml/csc412/dag.md
      - aiml/csc412/inference.md
      - aiml/csc412/mc.md
      - aiml/csc412/sampling.md
      - aiml/csc412/vi.md
      - aiml/csc412/vae.md
    - CSC311 Intro. Machine Learning:
      - aiml/csc311/knn.md
      - aiml/csc311/bvd.md
      - aiml/csc311/decision_trees.md
      - aiml/csc311/linear_regression.md
      - aiml/csc311/svm.md
      - aiml/csc311/neural_nets.md
      - aiml/csc311/gradient_descent.md
      - aiml/csc311/classification.md
      - aiml/csc311/probabilistic_models.md
      - aiml/csc311/pca.md
      - aiml/csc311/kM_EM.md
      - aiml/csc311/matrix_factorization.md
      - aiml/csc311/reinforce_learning.md
    - CSC384 Intro. Artificial Intelligence:
      - aiml/csc384/search.md
      - aiml/csc384/usearch.md
      - aiml/csc384/hsearch.md
      - aiml/csc384/csp.md
      - aiml/csc384/fc_gac.md

  - CS - General:
    - CSC488/2107 Compilers:
      - csg/csc488/intro.md
      - csg/csc488/parsing.md
      - csg/csc488/topdown_parsing.md
    - CS267C Applications of Parallel Computers:
      - csg/cs267/communication.md
      - csg/cs267/distributed.md
      - csg/cs267/dataparallel.md
      - csg/cs267/la.md
      - csg/cs267/random.md
      - csg/cs267/upcxx.md
      - csg/cs267/ml.md
      - csg/cs267/grid.md
      - csg/cs267/sparse_matrix.md
      - csg/cs267/fft.md
      - csg/cs267/sort.md
    - CSC367 Parallel Programming:
      - csg/csc367/hie.md
      - csg/csc367/matrix.md
      - csg/csc367/simd.md
      - csg/csc367/parallel.md
      - csg/csc367/pthread.md
      - csg/csc367/omp.md
      - csg/csc367/omp_for.md
      - csg/csc367/omp_sync.md
      - csg/csc367/mpi.md
      - csg/csc367/mpi_comm.md
      - csg/csc367/cuda.md
      - csg/csc367/cuda_opt.md
      - csg/csc367/slurm.md
    - CSC336 Numerical Methods:
      - csg/csc336/approx_error.md
      - csg/csc336/arithmetic.md
      - csg/csc336/arithmetic_examples.md
      - csg/csc336/norm.md
      - csg/csc336/matrix_conditioning.md
      - csg/csc336/lu_decomposition.md
      - csg/csc336/pivoting.md
      - csg/csc336/interpolations.md
      - csg/csc336/non_linear_equations.md
    - CSC343 Intro. Databases:
      - csg/csc343/ra.md
      - csg/csc343/sql_query.md
      - csg/csc343/sql_def.md
      - csg/csc343/sql_man.md
      - csg/csc343/rm.md
      - csg/csc343/fd.md
    - CSC373 Algorithms Design, Analysis and Complexity:
      - csg/csc373/greedy_algorithm.md
      - csg/csc373/dp.md
      - csg/csc373/network_flow.md
      - csg/csc373/lp.md
      - csg/csc373/p_np.md
      - csg/csc373/npc.md
      - csg/csc373/self_reducibility.md
      - csg/csc373/optimization_approximation.md
    - CSC265 Enriched Data Structures and Analysis:
      - csg/csc265/pq.md
      - csg/csc265/mq.md
      - csg/csc265/avl.md
      - csg/csc265/avl_app.md
      - csg/csc265/hashset.md
      - csg/csc265/random.md
      - csg/csc265/amortized.md
      - csg/csc265/disjoint_set.md
      - csg/csc265/bfs.md
      - csg/csc265/dfs.md

  - Mathematics:
    - MAT337 Intro. Real Analysis:
      - math/mat337/real_number_construction.md
      - math/mat337/extremum.md
      - math/mat337/mct_bwt.md
      - math/mat337/topology_reals.md
      - math/mat337/normed_space.md
      - math/mat337/inner_product_and_fourier.md
      - math/mat337/function_convergence.md
      - math/mat337/series.md
      - math/mat337/AAT.md
      - math/mat337/approximations.md
      - math/mat337/ODE.md
      - math/mat337/swt.md
    - MAT334 Complex Variables:
      - math/mat334/intro.md
      - math/mat334/functions.md
      - math/mat334/cont_diff.md
      - math/mat334/multi_val_func.md
      - math/mat334/integration.md
      - math/mat334/ct.md
      - math/mat334/cie.md
      - math/mat334/power_series.md
      - math/mat334/residue.md
      - math/mat334/jl.md
      - math/mat334/pvt.md
      - math/mat334/arg.md
      - math/mat334/conformal.md
    - MAT363 Geometry of Curves and Surfaces:
      - math/mat363/intro_curves.md
      - math/mat363/arc_length.md
      - math/mat363/reparam.md
      - math/mat363/curvature.md
      - math/mat363/plane_curve.md
      - math/mat363/space_curves.md
      - math/mat363/fvt.md
      - math/mat363/iso_ineq.md
      - math/mat363/intro_surface.md
      - math/mat363/surface_tangent.md
      - math/mat363/surface_normals.md
      - math/mat363/surface_examples.md
      - math/mat363/examples_smooth.md
      - math/mat363/fff.md
      - math/mat363/isometry.md
      - math/mat363/sff.md
      - math/mat363/gaussian_curvature.md
      - math/mat363/parallel_transport.md
      - math/mat363/geodesics.md
      - math/mat363/gcme.md
      - math/mat363/minimal_surface.md
      - math/mat363/gbt.md
    - APM462 Nonlinear Optimization:
      - math/apm462/calculus_review.md
      - math/apm462/ufdo.md
      - math/apm462/ufdoq.md
      - math/apm462/ecfdo.md
      - math/apm462/ecfdoq.md
      - math/apm462/icfdo.md
      - math/apm462/icfdoq.md
      - math/apm462/newtons_method_and_steepest_descent.md
      - math/apm462/conjugate.md
      - math/apm462/conjugateq.md
      - math/apm462/uo_functional.md
      - math/apm462/uo_functional_q.md
      - math/apm462/co_functional.md
      - math/apm462/co_functional_q.md
  - Statistics:
    - STA303/1002 Methods of Data Analysis II:
      - stats/sta303/Summary.md
      - stats/sta303/two_way_ANOVA.md
      - stats/sta303/multi_comparisons.md
      - stats/sta303/binary_logistic_regression.md
      - stats/sta303/case_spock.md
      - stats/sta303/binomial_logistic_regression.md
      - stats/sta303/poisson_regression.md
      - stats/sta303/contingency.md
    - STA347 Probability I:
      - stats/sta347/probability.md
      - stats/sta347/distribution.md
      - stats/sta347/mv_distribution.md
      - stats/sta347/function_rv.md
      - stats/sta347/expectations.md
      - stats/sta347/var.md
      - stats/sta347/ineq.md
    - STA355 Theory of Statistical Practice:
      - stats/sta355/statistical_models.md
      - stats/sta355/order_statistics.md
      - stats/sta355/spacings.md
      - stats/sta355/density_estimation.md
      - stats/sta355/methods_of_estimation.md
      - stats/sta355/bayes_inference.md
    - STA457/2202 Time Series Analysis:
      - stats/sta457/Summary.md
      - stats/sta457/Introduction.md
      - stats/sta457/ARMA.md
      - stats/sta457/ARIMA.md
      - stats/sta457/Forecasting.md
      - stats/sta457/VAR.md
      - stats/sta457/granger_causality_and_cointegration.md
  - Main: https://haoda-li.github.io/

theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Dark mode
    - scheme: slate
      accent: green
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy


plugins:
  - search
  - glightbox
  - plotly
  - autorefs
  - bibtex:
      bib_file: "notebook/assets/refs.bib"
      csl_file: "notebook/assets/acm-siggraph.csl"
      cite_inline: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - meta
  - tables
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['notebook']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - assets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/extra.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/haoda-li-515b26165/
    - icon: fontawesome/brands/github
      link: https://github.com/haoda-li/
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=e1Bif78AAAAJ

copyright: Copyright &copy; 2017 - 2024 | Haoda Li
